name: "Carbonz SolarAutopilot"
description: "Solar Assistant project and allows inverter changes over MQTT"
version: "1.1.0"
slug: "hello_world"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  2000/tcp: 2000